### ISSUE TITLE
Allow Disable User Registration

### ISSUE THREAD

**Issue by dernorberto** [arugifa/klougle#22]
The original StandardNotes server allows disabling user registration, see: https://github.com/standardnotes/syncing-server

I tried the same env on this server docker container and it had no effect.
DISABLE_USER_REGISTRATION=true

**Comment by arugifa** [comment]
Hi @dernorberto,

Thanks for the feedback!

I updated the image to use the new Standard Notes Server's [repository](https://github.com/standardnotes/syncing-server).

This should be fine now, by using the `latest` or `0.0.0-rc.2020.04.14` tags.
